function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -1; // obj_player
	global.__objectDepths[1] = 0; // obj_lazer
	global.__objectDepths[2] = 0; // obj_lazer_charge
	global.__objectDepths[3] = 0; // obj_lazer_bounce
	global.__objectDepths[4] = 0; // obj_lazer_homing
	global.__objectDepths[5] = 0; // obj_lazer_spec
	global.__objectDepths[6] = 0; // obj_lazer2
	global.__objectDepths[7] = 0; // obj_lazer_ball
	global.__objectDepths[8] = -2; // obj_enemy_lazer
	global.__objectDepths[9] = 0; // obj_missile
	global.__objectDepths[10] = 0; // obj_enemy_missile
	global.__objectDepths[11] = 0; // par_crystal
	global.__objectDepths[12] = 0; // par_ore
	global.__objectDepths[13] = 0; // obj_crystal
	global.__objectDepths[14] = 0; // obj_scrap
	global.__objectDepths[15] = 0; // obj_crystal5
	global.__objectDepths[16] = 0; // obj_repair
	global.__objectDepths[17] = 0; // obj_asteroid_spec
	global.__objectDepths[18] = 0; // obj_asteroid_small
	global.__objectDepths[19] = 0; // obj_asteroid
	global.__objectDepths[20] = 0; // obj_asteroid_large
	global.__objectDepths[21] = 0; // obj_gib
	global.__objectDepths[22] = -1; // obj_explosion
	global.__objectDepths[23] = 0; // obj_power_up
	global.__objectDepths[24] = 0; // obj_defense_power_up
	global.__objectDepths[25] = 0; // obj_upgrade
	global.__objectDepths[26] = 0; // obj_health_up
	global.__objectDepths[27] = 0; // obj_energy_up
	global.__objectDepths[28] = 0; // obj_attack_up
	global.__objectDepths[29] = 0; // obj_shield_up
	global.__objectDepths[30] = 0; // obj_broken_player
	global.__objectDepths[31] = 0; // obj_death_item
	global.__objectDepths[32] = 1; // obj_station
	global.__objectDepths[33] = 0; // obj_bomb
	global.__objectDepths[34] = 0; // obj_planet_parent
	global.__objectDepths[35] = 0; // obj_ship
	global.__objectDepths[36] = -1; // obj_enemy_ship
	global.__objectDepths[37] = -1; // obj_enemy_boss
	global.__objectDepths[38] = 0; // par_player
	global.__objectDepths[39] = 0; // obj_enemy_spawn
	global.__objectDepths[40] = 0; // obj_target
	global.__objectDepths[41] = -1; // obj_enemy_scout
	global.__objectDepths[42] = -1; // obj_enemy_scout2
	global.__objectDepths[43] = -1; // obj_enemy_scout3
	global.__objectDepths[44] = -1; // obj_enemy_fighter
	global.__objectDepths[45] = -1; // obj_enemy_fighter2
	global.__objectDepths[46] = -1; // obj_enemy_fighter3
	global.__objectDepths[47] = -1; // obj_enemy_bomber
	global.__objectDepths[48] = -1; // obj_enemy_bomber2
	global.__objectDepths[49] = -1; // obj_enemy_bomber3
	global.__objectDepths[50] = -1; // obj_enemy_frigate
	global.__objectDepths[51] = 0; // obj_button_next
	global.__objectDepths[52] = 0; // obj_button_prev
	global.__objectDepths[53] = 0; // obj_edit
	global.__objectDepths[54] = 0; // obj_button_exit
	global.__objectDepths[55] = 0; // obj_button_back
	global.__objectDepths[56] = 0; // par_button
	global.__objectDepths[57] = 0; // obj_stats
	global.__objectDepths[58] = 0; // obj_menu
	global.__objectDepths[59] = 0; // obj_pause_menu
	global.__objectDepths[60] = 0; // obj_store_menu
	global.__objectDepths[61] = 0; // obj_levelup_menu
	global.__objectDepths[62] = 0; // obj_material_sell_menu
	global.__objectDepths[63] = 0; // obj_buy_weapon_menu
	global.__objectDepths[64] = 0; // obj_hbar
	global.__objectDepths[65] = -1; // obj_hslider
	global.__objectDepths[66] = 0; // obj_mouse
	global.__objectDepths[67] = -1; // obj_vslider
	global.__objectDepths[68] = 0; // obj_vbar
	global.__objectDepths[69] = 1; // obj_planet
	global.__objectDepths[70] = 2; // obj_planet_dummy
	global.__objectDepths[71] = 1; // obj_asteroid_dummy
	global.__objectDepths[72] = 0; // obj_ps
	global.__objectDepths[73] = 0; // obj_init
	global.__objectDepths[74] = 1000; // obj_camera
	global.__objectDepths[75] = 0; // obj_pause
	global.__objectDepths[76] = 0; // obj_spawn
	global.__objectDepths[77] = 0; // obj_gametitle
	global.__objectDepths[78] = 0; // obj_music
	global.__objectDepths[79] = 0; // obj_generator
	global.__objectDepths[80] = 0; // obj_credits


	global.__objectNames[0] = "obj_player";
	global.__objectNames[1] = "obj_lazer";
	global.__objectNames[2] = "obj_lazer_charge";
	global.__objectNames[3] = "obj_lazer_bounce";
	global.__objectNames[4] = "obj_lazer_homing";
	global.__objectNames[5] = "obj_lazer_spec";
	global.__objectNames[6] = "obj_lazer2";
	global.__objectNames[7] = "obj_lazer_ball";
	global.__objectNames[8] = "obj_enemy_lazer";
	global.__objectNames[9] = "obj_missile";
	global.__objectNames[10] = "obj_enemy_missile";
	global.__objectNames[11] = "par_crystal";
	global.__objectNames[12] = "par_ore";
	global.__objectNames[13] = "obj_crystal";
	global.__objectNames[14] = "obj_scrap";
	global.__objectNames[15] = "obj_crystal5";
	global.__objectNames[16] = "obj_repair";
	global.__objectNames[17] = "obj_asteroid_spec";
	global.__objectNames[18] = "obj_asteroid_small";
	global.__objectNames[19] = "obj_asteroid";
	global.__objectNames[20] = "obj_asteroid_large";
	global.__objectNames[21] = "obj_gib";
	global.__objectNames[22] = "obj_explosion";
	global.__objectNames[23] = "obj_power_up";
	global.__objectNames[24] = "obj_defense_power_up";
	global.__objectNames[25] = "obj_upgrade";
	global.__objectNames[26] = "obj_health_up";
	global.__objectNames[27] = "obj_energy_up";
	global.__objectNames[28] = "obj_attack_up";
	global.__objectNames[29] = "obj_shield_up";
	global.__objectNames[30] = "obj_broken_player";
	global.__objectNames[31] = "obj_death_item";
	global.__objectNames[32] = "obj_station";
	global.__objectNames[33] = "obj_bomb";
	global.__objectNames[34] = "obj_planet_parent";
	global.__objectNames[35] = "obj_ship";
	global.__objectNames[36] = "obj_enemy_ship";
	global.__objectNames[37] = "obj_enemy_boss";
	global.__objectNames[38] = "par_player";
	global.__objectNames[39] = "obj_enemy_spawn";
	global.__objectNames[40] = "obj_target";
	global.__objectNames[41] = "obj_enemy_scout";
	global.__objectNames[42] = "obj_enemy_scout2";
	global.__objectNames[43] = "obj_enemy_scout3";
	global.__objectNames[44] = "obj_enemy_fighter";
	global.__objectNames[45] = "obj_enemy_fighter2";
	global.__objectNames[46] = "obj_enemy_fighter3";
	global.__objectNames[47] = "obj_enemy_bomber";
	global.__objectNames[48] = "obj_enemy_bomber2";
	global.__objectNames[49] = "obj_enemy_bomber3";
	global.__objectNames[50] = "obj_enemy_frigate";
	global.__objectNames[51] = "obj_button_next";
	global.__objectNames[52] = "obj_button_prev";
	global.__objectNames[53] = "obj_edit";
	global.__objectNames[54] = "obj_button_exit";
	global.__objectNames[55] = "obj_button_back";
	global.__objectNames[56] = "par_button";
	global.__objectNames[57] = "obj_stats";
	global.__objectNames[58] = "obj_menu";
	global.__objectNames[59] = "obj_pause_menu";
	global.__objectNames[60] = "obj_store_menu";
	global.__objectNames[61] = "obj_levelup_menu";
	global.__objectNames[62] = "obj_material_sell_menu";
	global.__objectNames[63] = "obj_buy_weapon_menu";
	global.__objectNames[64] = "obj_hbar";
	global.__objectNames[65] = "obj_hslider";
	global.__objectNames[66] = "obj_mouse";
	global.__objectNames[67] = "obj_vslider";
	global.__objectNames[68] = "obj_vbar";
	global.__objectNames[69] = "obj_planet";
	global.__objectNames[70] = "obj_planet_dummy";
	global.__objectNames[71] = "obj_asteroid_dummy";
	global.__objectNames[72] = "obj_ps";
	global.__objectNames[73] = "obj_init";
	global.__objectNames[74] = "obj_camera";
	global.__objectNames[75] = "obj_pause";
	global.__objectNames[76] = "obj_spawn";
	global.__objectNames[77] = "obj_gametitle";
	global.__objectNames[78] = "obj_music";
	global.__objectNames[79] = "obj_generator";
	global.__objectNames[80] = "obj_credits";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
